version: '3'
services:
  eosio:
    image: eosio/eos-dev:v1.1.0
    container_name: eosio
    command: /docker-entrypoint.sh
    ports:
      - "8888:8888"
      - "9876:9876"
    volumes:
      - "./docker-entrypoint.sh:/docker-entrypoint.sh"
      - "./:/work"
      - "./eosio_mount/data:/mnt/dev/data"
